PLANET-3182 Create codeception wpunit suite
greenpeace/planet4-base pull request #15
Opened 2019-01-31 10:37 UTC by kirdia

**Work in progress** 

### Working with wpunit tests
I have included a sample test that contains commands that can be used in a WP_UnitTestCase test (like the factories).

https://github.com/greenpeace/planet4-base-fork/blob/planet-3182/tests/wpunit/Sample/SampleTest.php

More information you can find here.
https://codeception.com/for/wordpress
https://github.com/lucatume/wp-browser#wploader-configuration

You can generate wpunit test class
`vendor/bin/codecept generate:wpunit wpunit SomeClass`

----------------------------
### Wpunit suite database
A separate database should be used for wpunit suite (the same way unit tests in planet4-master-theme planet4-plugin-blocks work). WPLoader will drop some tables before the tests execution.
The configuration for the second db could be set here:

https://github.com/greenpeace/planet4-base-fork/blob/planet-3182/.env.codeception#L14 (we should keep it only for ci)
https://github.com/greenpeace/planet4-base-fork/blob/planet-3182/tests/wpunit.suite.yml#L16 (suite's general config)
https://github.com/greenpeace/planet4-base-fork/blob/planet-3182/tests/_envs/dev.yml#L13 (specific environment config)

>   The following tables will be dropped when running the suite: 
>   	- posts
>   	- comments
>   	- links
>   	- options
>   	- postmeta
>   	- terms
>   	- term_taxonomy
>   	- term_relationships
>   	- termmeta
>   	- commentmeta

----------------------------
### Local environment configuration
You can override the repo's configuration to match your local env.

https://codeception.com/docs/07-AdvancedUsage#Environments

You can generate an env file with this, passing the env name
`vendor/bin/codecept generate:env dev`

Then your local config can be used with the switch --env
`vendor/bin/codecept run acceptance --env your_env_filename`
`vendor/bin/codecept run wpunit --env your_env_filename`

I have included a sample env file just for reference.
You can override the general or suite configuration using an env file:
https://github.com/greenpeace/planet4-base-fork/blob/planet-3182/tests/_envs/dev.yml

2019-03-21 22:43 UTC, 27Bslash6 requested changes
Lint errors. Have you run `make init` and confirmed the pre-commit hooks are linting code?

2019-04-03 03:56 UTC, 27Bslash6 approved these changes

2019-04-03 05:23 UTC, 27Bslash6 commented
LGTM

2019-04-03 08:28 UTC, angtheod approved these changes
same here

2019-04-03 08:28 UTC, merged